# Назначение роли для аккаунта developer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-role-binding
subjects:
  - kind: User
    name: developer
roleRef:
  kind: ClusterRole
  name: developer-role
  apiGroup: ""

---
# Назначение роли для аккаунта admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
subjects:
  - kind: User
    name: admin
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: ""

---
# Назначение роли для аккаунта security
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: secret-manager-binding
subjects:
  - kind: User
    name: security
roleRef:
  kind: ClusterRole
  name: secret-manager
  apiGroup: ""

---
# Назначение роли для аккаунта devops
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: devops-role-binding
subjects:
  - kind: User
    name: devops
roleRef:
  kind: ClusterRole
  name: devops-role
  apiGroup: ""