# Назначение роли для сервисного аккаунта developer
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-role-binding
subjects:
  - kind: User
    name: developer
roleRef:
  kind: ClusterRole
  name: developer-role
  apiGroup: ""

---
# Назначение роли для сервисного аккаунта admin
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-role-binding
subjects:
  - kind: User
    name: admin
roleRef:
  kind: ClusterRole
  name: admin-role
  apiGroup: ""